CREATE DATABASE Naturista_Aura;
USE Naturista_Aura;	

CREATE TABLE Productos(
IdProducto INT UNSIGNED AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(255) NOT NULL,
IdCategoria INT UNSIGNED NOT NULL,
Descripcion TEXT NULL,
Precio DECIMAL(8,2) NOT NULL,
Producto_imagen BLOB,
Eliminado VARCHAR(1),
PRIMARY KEY(IdProducto),
CONSTRAINT FK_PRO_CAT FOREIGN KEY(IdCategoria) REFERENCES Categorias(IdCategoria) ON UPDATE CASCADE
);

CREATE TABLE Categorias(
IdCategoria INT UNSIGNED AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(255) NULL,
Eliminado VARCHAR(1),
PRIMARY KEY(IdCategoria)
);

CREATE TABLE Servicios(
IdServicio INT UNSIGNED AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Descripcion TEXT NULL,
Precio DECIMAL(8,2) NOT NULL,
Eliminado VARCHAR(1),
PRIMARY KEY(IdServicio)
);

CREATE TABLE Usuarios(
IdUsuario INT UNSIGNED AUTO_INCREMENT NOT NULL, 
NombreCompleto VARCHAR(255) NULL,
Usuario VARCHAR(20) NOT NULL,
PASSWORD VARCHAR(100) NULL,
Eliminado VARCHAR(1),
PRIMARY KEY(IdUsuario)
);